### Puxar base de dados

In [30]:
import pandas as pd
base_dados_df = pd.read_csv(r"exportacoes_franca.csv")
display(base_dados_df)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

### Informações Gerais

Quantas linhas têm a tabela? Existe algum valor vazio que deveria ser tratado?

In [31]:
display(base_dados_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  str
 3   City             142360 non-null  str
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  str
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  str
 8   Economic Block   142360 non-null  str
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), str(5)
memory usage: 40.8 MB

None

### Como foi a evolução das exportações para a frança ao longo dos anos?

Crie uma tabela com os anos de 2016, 2017, 2018, 2019 e 2020 e o valor US$ de exportações

In [32]:
base_anos_valor = base_dados_df[["Year", "US$ FOB"]].groupby("Year").sum()
def formatar_numero(valor):
    valor_formatado = f"US${valor:,}"
    return valor_formatado
base_anos_valor["US$ FOB"] = base_anos_valor["US$ FOB"].apply(formatar_numero)
display(base_anos_valor)

               US$ FOB
Year
2016  US$4,615,500,082
2017  US$4,448,705,456
2018  US$5,239,424,416
2019  US$5,218,723,612
2020  US$3,967,594,810

### Quais os produtos mais exportados ao longo de todo o período?

Queremos saber os produtos com maior valor US$ de exportação

In [33]:
base_produtos_mais_export = base_dados_df[["SH2 Description", "US$ FOB"]].groupby("SH2 Description").sum()
base_produtos_mais_export = base_produtos_mais_export.sort_values(by="US$ FOB", ascending=False)

#formatar sempre por ultimo
base_produtos_mais_export["US$ FOB"] = base_produtos_mais_export["US$ FOB"].apply(formatar_numero)
display(base_produtos_mais_export)

                                                             US$ FOB
SH2 Description
Residues and waste from the food industries; ot...  US$5,641,498,484
Ores, slag and ash                                  US$3,404,353,274
Nuclear reactors, boilers, machinery and mechan...  US$1,889,781,694
Pulp of wood or of other fibrous cellulosic mat...  US$1,855,424,642
Aircraft, spacecraft, and parts thereof             US$1,253,007,710
...                                                              ...
Umbrellas, sun umbrellas, walking-sticks, seat-...         US$18,872
Cork and articles of cork                                  US$10,974
Wool, fine or coarse animal hair; horsehair yar...          US$2,540
Tin and articles thereof                                    US$2,460
Photographic or cinematographic goods                         US$148

[97 rows x 1 columns]

### Em 2020 qual cidade mais exportou para a França?
Em valores US$

In [34]:
base_2020 = base_dados_df.loc[base_dados_df["Year"]==2020, :]

base_2020_city = base_2020[["City", "US$ FOB"]].groupby("City").sum()
base_2020_city = base_2020_city.sort_values(by="US$ FOB", ascending=False)
base_2020_city["US$ FOB"] = base_2020_city["US$ FOB"].apply(formatar_numero)
display(base_2020_city)

                                    US$ FOB
City
Duque de Caxias - RJ         US$279,405,596
Luís Eduardo Magalhães - BA  US$265,328,132
Ponta Grossa - PR            US$187,777,016
São José dos Campos - SP     US$172,939,276
Rio de Janeiro - RJ          US$122,522,214
...                                     ...
Não-Me-Toque - RS                     US$42
Cubatão - SP                          US$40
Holambra - SP                         US$10
São Sebastião do Caí - RS              US$6
Quatro Pontes - PR                     US$0

[648 rows x 1 columns]

### Quais os produtos mais exportados (em US$) que as 2 maiores cidades (em exportação em 2020) exportaram?

In [ ]:
cidade = base_2020_city.index[0]

base_dados_cidade = base_2020.loc[base_2020["City"]==cidade]

base_produtos_cidade = base_dados_cidade[["SH2 Description", "US$ FOB"]].groupby("SH2 Description").sum()

base_produtos_cidade = base_produtos_cidade.sort_values(by="US$ FOB", ascending=False)

base_produtos_cidade["US$ FOB"] = base_produtos_cidade["US$ FOB"].apply(formatar_numero)

print(f"Produtos mais exportados da Cidade: {cidade}")
display(base_produtos_cidade)

Produtos mais exportados da Cidade: Duque de Caxias - RJ

                                                           US$ FOB
SH2 Description
Nuclear reactors, boilers, machinery and mechan...  US$185,816,982
Mineral fuels, mineral oils, bituminous substan...   US$67,355,688
Articles of iron or steel                             US$9,118,714
Residues and waste from the food industries; ot...    US$4,014,274
Optical, photographic, cinematographic instrume...    US$3,013,092
Nickel and articles thereof                           US$2,951,286
Electrical machinery and equipment and parts th...    US$2,595,048
Lead and articles thereof                             US$1,660,180
Rubber and articles thereof                           US$1,379,296
Organic chemicals                                       US$535,136
Vehicles other than railway or tramway rolling-...      US$353,958
Plastics and articles thereof                           US$228,638
Aluminium and articles thereof                          US$168,522
Copper and articles thereof                             US$138,466
Tools, implements, cutlery, spoons and forks, o...       US$33,864
Articles of stone, plaster, cement, asbestos, m...       US$16,856
Miscellaneous chemical products                          US$11,984
Glass and glassware                                       US$8,430
Railway or tramway locomotives, rolling-stock a...        US$3,666
Paper and paperboard; articles of paper pulp, o...        US$1,516